Fixes

diff --git a/ziskup/ziskup b/ziskup/ziskup
--- a/ziskup/ziskup
+++ b/ziskup/ziskup
@@ -49,6 +49,20 @@ main() {
     --nokey)
       SETUP_KEY="none"
       ;;
+    --gpu)
+      if [[ "${USE_GPU}" == "false" ]]; then
+        err "--gpu and --cpu are mutually exclusive"
+        exit 1
+      fi
+      USE_GPU=true
+      ;;
+    --cpu)
+      if [[ "${USE_GPU}" == "true" ]]; then
+        err "--gpu and --cpu are mutually exclusive"
+        exit 1
+      fi
+      USE_GPU=false
+      ;;
     -h | --help)
       usage
       exit 0
@@ -117,32 +131,37 @@ main() {
   if [[ -n "${GH_RUNNER}" ]]; then
     warn "Running from GitHub action, installing proving key"
     SETUP_KEY="proving"
+    USE_GPU=false
   fi
 
-  # Determine whether to use GPU or CPU-only binaries (linux only)
-  USE_GPU=false
+  # Determine whether to use GPU or CPU binaries (linux only)
   if [ "${PLATFORM}" = "linux" ]; then
     if [ "${HAS_CUDA}" = "true" ]; then
       USE_GPU=true
     else
-      warn "NVIDIA CUDA was not detected on this system"
-      say "The version with only CPU support will be installed by default"
-      say ""
-      say "Do you want to:"
-      say "  1) Install CPU version (default - just press enter)"
-      say "  2) Install GPU version"
-      read -p ">" cuda_choice < /dev/tty
-      cuda_choice=${cuda_choice:-1}
+      if [[ -z "${USE_GPU}" ]]; then
+        warn "NVIDIA CUDA was not detected on this system"
+        say "The version with only CPU support will be installed by default"
+        say ""
+        say "Do you want to:"
+        say "  1) Install CPU version (default - just press enter)"
+        say "  2) Install GPU version"
+        read -p ">" cuda_choice < /dev/tty
+        cuda_choice=${cuda_choice:-1}
 
-      case "${cuda_choice}" in
-        1) USE_GPU=false ;;
-        2) USE_GPU=true ;;
-        *)
-          err "invalid option, aborting installation"
-          exit 1
-          ;;
-      esac
+        case "${cuda_choice}" in
+          1) USE_GPU=false ;;
+          2) USE_GPU=true ;;
+          *)
+            err "invalid option, aborting installation"
+            exit 1
+            ;;
+        esac
+      fi
     fi
+  else
+    # For macOS, we only install the CPU version as GPU support is not available yet
+    USE_GPU=false
   fi
 
   # Ask user about key installation if SETUP_KEY is not set
