fix release gha

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -1,5 +1,3 @@
-# Reference: https://github.com/foundry-rs/foundry/blob/master/.github/workflows/release.yml
-
 name: release
 
 on:
@@ -8,10 +6,6 @@ on:
       - "v*.*.*"
   workflow_dispatch:
 
-env:
-  CARGO_TERM_COLOR: always
-  IS_TEST: 'true'  # o el valor correspondiente
-
 permissions:
   contents: write
   pull-requests: read
@@ -19,20 +13,13 @@ permissions:
 jobs:
   prepare:
     name: Prepare release
-    runs-on: ubuntu-latest
+    runs-on: ubuntu-22.04
     timeout-minutes: 30
     outputs:
       tag_name: ${{ steps.release_info.outputs.tag_name }}
       release_name: ${{ steps.release_info.outputs.release_name }}
     steps:
       - uses: actions/checkout@v4
-        with:
-          fetch-depth: 0
-
-      - name: Setup CI
-        uses: ./.github/actions/setup
-        with:
-          pull_token: ${{ secrets.PULL_TOKEN }}
 
       - name: Set test flag
         run: |
@@ -42,7 +29,7 @@ jobs:
             echo "IS_TEST=false" >> $GITHUB_ENV
           fi
 
-      # If it's a test release, tag with the release time. Else, use the tag name as is.
+      # If it's a test release, tag with the release date. Else, use the tag name as is.
       - name: Compute release name and tag
         id: release_info
         run: |
@@ -63,7 +50,7 @@ jobs:
           fi
 
   release:
-    name: ${{ matrix.target }} (${{ matrix.runner }})
+    name: Build ${{ matrix.target }} (${{ matrix.runner }})
     runs-on: ${{ matrix.runner }}
     timeout-minutes: 240
     needs: prepare
@@ -75,7 +62,7 @@ jobs:
           # `target`: Rust build target triple
           # `platform` and `arch`: Used in tarball names
           # `svm`: target platform to use for the Solc binary: https://github.com/roynalnaruto/svm-rs/blob/84cbe0ac705becabdc13168bae28a45ad2299749/svm-builds/build.rs#L4-L24
-          - runner: ubuntu-latest
+          - runner: ubuntu-22.04
             target: x86_64-unknown-linux-gnu
             svm_target_platform: linux-amd64
             platform: linux
@@ -99,152 +86,42 @@ jobs:
           #   target: x86_64-pc-windows-msvc
           #   svm_target_platform: windows-amd64
           #   platform: win32
-          #   arch: amd64
+          #   arch: amd64            
     steps:
       - uses: actions/checkout@v4
-
-      - name: Install Protoc
-        uses: arduino/setup-protoc@v3
-        with:
-          repo-token: ${{ secrets.GITHUB_TOKEN }}
-
-      - name: Install libraries
-        shell: bash
-        run: |
-          sudo apt-get update && sudo apt-get install -y \
-            clang nlohmann-json3-dev build-essential libbenchmark-dev \
-            libomp-dev libgmp-dev nasm libsodium-dev cmake openmpi-bin \
-            openmpi-common libopenmpi-dev
-
-      - name: Install Intel OpenMP
-        shell: bash
-        run: |
-          # download the key to system keyring
-          wget -O- https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS.PUB \
-          | gpg --dearmor | sudo tee /usr/share/keyrings/oneapi-archive-keyring.gpg > /dev/null
-
-          # add signed entry to apt sources and configure the APT client to use Intel repository:
-          echo "deb [signed-by=/usr/share/keyrings/oneapi-archive-keyring.gpg] https://apt.repos.intel.com/oneapi all main" | sudo tee /etc/apt/sources.list.d/oneAPI.list
-          sudo apt-get update
-          sudo apt-get install -y intel-oneapi-openmp
 
       - name: Install rust toolchain
         id: rustc-toolchain
         uses: actions-rs/toolchain@v1
         with:
           toolchain: stable
-          profile: minimal
+          profile: default
           override: true
-          target: ${{ matrix.target }}
+          target: x86_64-unknown-linux-gnu
 
-      - uses: Swatinem/rust-cache@v2
-        with:
-          key: ${{ matrix.target }}
-          cache-on-failure: true
-
-      - name: Set up git private repo access
-        run: |
-          git config --global url."https://${{ secrets.ZISK_CI_TOKEN }}@github.com/".insteadOf ssh://git@github.com
-          git config --global url."https://${{ secrets.ZISK_CI_TOKEN }}@github.com".insteadOf https://github.com
-
-      - name: Apple M1 setup
-        if: matrix.target == 'aarch64-apple-darwin'
-        run: |
-          echo "SDKROOT=$(xcrun -sdk macosx --show-sdk-path)" >> $GITHUB_ENV
-          echo "MACOSX_DEPLOYMENT_TARGET=$(xcrun -sdk macosx --show-sdk-platform-version)" >> $GITHUB_ENV
-
-      - name: Linux ARM setup
-        if: matrix.target == 'aarch64-unknown-linux-gnu'
-        run: |
-          sudo apt-get update -y
-          sudo apt-get install -y gcc-aarch64-linux-gnu
-          echo "CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_LINKER=aarch64-linux-gnu-gcc" >> $GITHUB_ENV
-
-      - name: Build binaries
-        env:
-          SVM_TARGET_PLATFORM: ${{ matrix.svm_target_platform }}
+      - name: Install dependencies
         shell: bash
         run: |
-          set -eo pipefail
-          target="${{ matrix.target }}"
-          flags=()
+            sudo apt-get install -y xz-utils jq curl build-essential qemu-system libomp-dev \
+                libgmp-dev nlohmann-json3-dev protobuf-compiler uuid-dev libgrpc++-dev \
+                libsecp256k1-dev libsodium-dev libpqxx-dev nasm
 
-          echo "🔍 Starting build process..."
-
-          # Debug: Show system info
-          echo "🖥️  System Info:"
-          uname -a
-          lsb_release -a || true
-
-          # Debug: Check if libiomp5.so is installed
-          echo "🔍 Searching for libiomp5.so on the system..."
-          IOMP5_PATH=$(find / -name "libiomp5.so" -type f 2>/dev/null | head -n 1 || true)
-
-          if [ -z "$IOMP5_PATH" ]; then
-            echo "❌ libiomp5.so not found on the system!"
-            echo "Attempting to list Intel OpenMP installation..."
-            dpkg -l | grep intel || echo "Intel OpenMP package not found."
-            exit 1
-          else
-            echo "✅ Found libiomp5.so at: $IOMP5_PATH"
-          fi
-
-          # Extract directory path from found libiomp5.so
-          IOMP5_DIR=$(dirname "$IOMP5_PATH")
-          echo "Using IOMP5_DIR: $IOMP5_DIR"
-
-          # Set LD_LIBRARY_PATH
-          export LD_LIBRARY_PATH="$IOMP5_DIR:$LD_LIBRARY_PATH"
-          echo "LD_LIBRARY_PATH set to: $LD_LIBRARY_PATH"
-
-          # Debug: Check linker search paths
-          echo "🔍 Verifying linker search paths for libiomp5..."
-          ldconfig -p | grep libiomp5 || echo "libiomp5 not found in ldconfig cache."
-
-          # Handle Windows executable suffix
-          [[ "$target" == *windows* ]] && exe=".exe"
-
-          # RUSTFLAGS with correct path for building binaries
-          export RUSTFLAGS="-C target-feature=+crt-static -L${IOMP5_DIR} -liomp5"
-          echo "RUSTFLAGS set to: $RUSTFLAGS"
-
-          # Build bins
-          echo "🚀 Starting cargo bins build..."
-          cargo build --release -p cargo-zisk -p ziskemu -p riscv -p zisk-core --target "$target" "${flags[@]}"
-
-          # RUSTFLAGS with correct path for building libzisk_witness.so
-          export RUSTFLAGS="-L${IOMP5_DIR} -liomp5"
-          echo "RUSTFLAGS set to: $RUSTFLAGS"
-
-          # Build libzisk_witness.so
-          echo "🚀 Starting libzisk_witness.so build..."
-          cargo build --release -p zisk-witness --target "$target" "${flags[@]}"
-
-          # Verify built binaries
-          bins=(cargo-zisk ziskemu riscv2zisk)
-          for name in "${bins[@]}"; do
-            bin=./target/$target/release/$name$exe
-            echo "🔍 Verifying binary: $bin"
-            file "$bin" || echo "⚠️  file command failed on $bin"
-            ldd "$bin" || echo "⚠️  ldd command failed on $bin"
-            if [[ "$name" != "riscv2zisk" ]]; then
-              $bin --version || echo "⚠️  Running $bin --version failed"
-            fi
-          done
-
-          # Verify built libraries
-          libraries=(libzisk_witness.so)
-          for name in "${libraries[@]}"; do
-            bin=./target/$target/release/$name
-            echo "🔍 Verifying binary library: $bin"
-            file "$bin" || echo "⚠️  file command failed on $bin"
-            ldd "$bin" || echo "⚠️  ldd command failed on $bin"
-          done
-
-          echo "✅ Build process completed."
-
-      - name: Set VERSION_NAME
-        run: echo "VERSION_NAME=$([ \"$IS_TEST\" == 'true' ] && echo 'test' || echo '${{ needs.prepare.outputs.tag_name }}')" >> $GITHUB_ENV
+      - name: Build binaries
+        shell: bash
+        run: |
+            cargo build --release --target "${{ matrix.target }}"
+            
+            # Verify built binaries
+            bins=(cargo-zisk ziskemu riscv2zisk libzisk_witness.so)
+            for name in "${bins[@]}"; do
+                bin=./target/$target/release/$name$exe
+                echo "🔍 Verifying binary: $bin"
+                file "$bin" || echo "⚠️  file command failed on $bin"
+                ldd "$bin" || echo "⚠️  ldd command failed on $bin"
+                if [[ "$name" = "cargo-zisk" ]]; then
+                $bin --version || echo "⚠️  Running $bin --version failed"
+                fi
+            done
 
       - name: Archive binaries
         id: artifacts
@@ -252,44 +129,35 @@ jobs:
           PLATFORM_NAME: ${{ matrix.platform }}
           TARGET: ${{ matrix.target }}
           ARCH: ${{ matrix.arch }}
-          VERSION_NAME: ${{ env.VERSION_NAME }}
         shell: bash
         run: |
-          if [ "$PLATFORM_NAME" == "linux" ]; then
-            tar -czvf "cargo_zisk_${PLATFORM_NAME}_${ARCH}.tar.gz" \
-              --transform 's/.*\///' \
+          if [ "$PLATFORM_NAME" == "linux" ] || [ "$PLATFORM_NAME" == "darwin" ]; then
+            ARCHIVE_FILE="cargo_zisk_${PLATFORM_NAME}_${ARCH}.tar.gz"
+
+            TAR_CMD="tar"
+            [ "$PLATFORM_NAME" == "darwin" ] && TAR_CMD="gtar"
+
+            $TAR_CMD -czvf "$ARCHIVE_FILE" --transform 's/.*\///' \
               ./target/${TARGET}/release/cargo-zisk \
               ./target/${TARGET}/release/ziskemu \
               ./target/${TARGET}/release/riscv2zisk \
               ./target/${TARGET}/release/libzisk_witness.so \
               ./precompiles/keccakf/src/keccakf_script.json \
               ./ziskup/ziskup
-
-            echo "file_name=cargo_zisk_${PLATFORM_NAME}_${ARCH}.tar.gz" >> $GITHUB_OUTPUT
-          elif [ "$PLATFORM_NAME" == "darwin" ]; then
-            # We need to use gtar here otherwise the archive is corrupt.
-            # See: https://github.com/actions/virtual-environments/issues/2619
-            gtar -czvf "cargo_zisk_${PLATFORM_NAME}_${ARCH}.tar.gz" \
-              --transform 's/.*\///' \
-              ./target/${TARGET}/release/cargo-zisk \
-              ./target/${TARGET}/release/ziskemu \
-              ./target/${TARGET}/release/riscv2zisk \
-              ./target/${TARGET}/release/libzisk_witness.so \
-              ./precompiles/keccakf/src/keccakf_script.json \
-              ./ziskup/ziskup
-
-            echo "file_name=cargo_zisk_${PLATFORM_NAME}_${ARCH}.tar.gz" >> $GITHUB_OUTPUT
           else
-            7z a -tzip -ep1 "cargo_zisk_${PLATFORM_NAME}_${ARCH}.zip" \
-              ./target/${TARGET}/cargo-zisk.exe ./target/${TARGET}/ziskemu.exe ./target/${TARGET}/riscv2zisk.exe \
+            ARCHIVE_FILE="cargo_zisk_${PLATFORM_NAME}_${ARCH}.zip"
+            7z a -tzip -ep1 "$ARCHIVE_FILE" \
+              ./target/${TARGET}/release/cargo-zisk.exe \
+              ./target/${TARGET}/releaseziskemu.exe \
+              ./target/${TARGET}/release/riscv2zisk.exe \
               ./precompiles/keccakf/src/keccakf_script.json \
               ./ziskup/ziskup
 
-            mv "cargo_zisk_${PLATFORM_NAME}_${ARCH}.zip" ../../../
-            echo "file_name=cargo_zisk_${PLATFORM_NAME}_${ARCH}.zip" >> $GITHUB_OUTPUT
+            mv "$ARCHIVE_FILE" ../../../
           fi
 
-      # Creates the release for this specific version
+          echo "file_name=$ARCHIVE_FILE" >> $GITHUB_OUTPUT       
+        
       - name: Create release
         uses: softprops/action-gh-release@v2
         env:
@@ -297,8 +165,7 @@ jobs:
         with:
           name: ${{ needs.prepare.outputs.release_name }}
           tag_name: ${{ needs.prepare.outputs.tag_name }}
-          draft: ${{ env.IS_TEST == 'true' }}
+          draft: true
           make_latest: "false"
           files: |
-            ${{ steps.artifacts.outputs.file_name }}
-
+            ${{ steps.artifacts.outputs.file_name }}          
