Pre develop 0.4.2 (#275)
* Move ziskup to main branch URLs
* Improve documentation
* Removing hardcoded path from keccakfs (#274)

Co-authored-by: fractasy <fractasy@gmail.com>
Co-authored-by: Héctor Masip Ardevol <hmasip@polygon.technology>
Co-authored-by: agnusmor <agnusmor@gmail.com>

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -10,6 +10,7 @@ on:
 
 env:
   CARGO_TERM_COLOR: always
+  IS_TEST: 'true'  # o el valor correspondiente
 
 permissions:
   contents: write
@@ -23,7 +24,6 @@ jobs:
     outputs:
       tag_name: ${{ steps.release_info.outputs.tag_name }}
       release_name: ${{ steps.release_info.outputs.release_name }}
-      changelog: ${{ steps.build_changelog.outputs.changelog }}
     steps:
       - uses: actions/checkout@v4
         with:
@@ -34,62 +34,33 @@ jobs:
         with:
           pull_token: ${{ secrets.PULL_TOKEN }}
 
-      - name: Set nightly flag
+      - name: Set test flag
         run: |
-          if [[ "${{ github.event_name }}" == "schedule" || "${{ github.event_name }}" == "workflow_dispatch" ]]; then
-            echo "IS_NIGHTLY=true" >> $GITHUB_ENV
+          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
+            echo "IS_TEST=true" >> $GITHUB_ENV
           else
-            echo "IS_NIGHTLY=false" >> $GITHUB_ENV
+            echo "IS_TEST=false" >> $GITHUB_ENV
           fi
 
-      # If it's a nightly release, tag with the release time. If the tag is `develop`, we want to use
-      # `latest` as the tag name. Else, use the tag name as is.
+      # If it's a test release, tag with the release time. Else, use the tag name as is.
       - name: Compute release name and tag
         id: release_info
         run: |
-          echo "IS_NIGHTLY=$IS_NIGHTLY"
+          echo "IS_TEST=$IS_TEST"
           echo "GITHUB_REF_NAME=$GITHUB_REF_NAME"
 
-          if [[ $IS_NIGHTLY == "true" ]]; then
-            echo "IS_NIGHTLY"
-            echo "tag_name=nightly-${GITHUB_SHA}"
-            echo "release_name=Nightly ($(date '+%Y-%m-%d'))"
-            echo "tag_name=nightly-${GITHUB_SHA}" >> $GITHUB_OUTPUT
-            echo "release_name=Nightly ($(date '+%Y-%m-%d'))" >> $GITHUB_OUTPUT
-          elif [[ "${GITHUB_REF_NAME}" == "develop" ]]; then
-            echo "IS_LATEST"
-            echo "tag_name=latest"
-            echo "release_name=Latest"
-            echo "tag_name=latest" >> $GITHUB_OUTPUT
-            echo "release_name=Latest" >> $GITHUB_OUTPUT
+          if [[ $IS_TEST == "true" ]]; then
+            echo "IS_TEST"
+            echo "tag_name=test-${GITHUB_SHA}"
+            echo "release_name=Test ($(date '+%Y-%m-%d'))"
+            echo "tag_name=test-${GITHUB_SHA}" >> $GITHUB_OUTPUT
+            echo "release_name=Test ($(date '+%Y-%m-%d'))" >> $GITHUB_OUTPUT
           else
+            echo "tag_name=${GITHUB_REF_NAME}"
+            echo "release_name=${GITHUB_REF_NAME}"
             echo "tag_name=${GITHUB_REF_NAME}" >> $GITHUB_OUTPUT
             echo "release_name=${GITHUB_REF_NAME}" >> $GITHUB_OUTPUT
           fi
-
-      # Creates a `nightly-SHA` tag for this specific nightly
-      # This tag is used for this specific nightly version's release
-      # which allows users to roll back. It is also used to build
-      # the changelog.
-      - name: Create build-specific nightly tag
-        if: ${{ env.IS_NIGHTLY == 'true' }}
-        uses: actions/github-script@v7
-        env:
-          TAG_NAME: ${{ steps.release_info.outputs.tag_name }}
-        with:
-          script: |
-            const createTag = require('./.github/scripts/create-tag.js')
-            await createTag({ github, context }, process.env.TAG_NAME)
-
-      - name: Build changelog
-        id: build_changelog
-        uses: mikepenz/release-changelog-builder-action@v4
-        with:
-          configuration: "./.github/changelog.json"
-          fromTag: ${{ env.IS_NIGHTLY == 'true' && 'nightly' || '' }}
-          toTag: ${{ steps.release_info.outputs.tag_name }}
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
   release:
     name: ${{ matrix.target }} (${{ matrix.runner }})
@@ -157,18 +128,6 @@ jobs:
           sudo apt-get update
           sudo apt-get install -y intel-oneapi-openmp
 
-      # - name: Verify libiomp5 installation
-      #   run: |
-      #     find /usr -name "libiomp5*"
-      #     ls -l /usr/lib/x86_64-linux-gnu/libiomp5.*
-      #     echo $LD_LIBRARY_PATH
-
-      # - name: Set LD_LIBRARY_PATH
-      #   run: echo "LD_LIBRARY_PATH=/usr/lib/x86_64-linux-gnu:$LD_LIBRARY_PATH" >> $GITHUB_ENV
-
-      - name: Set LD_LIBRARY_PATH for OpenMP
-        run: echo "LD_LIBRARY_PATH=/usr/lib/x86_64-linux-gnu:/usr/lib/llvm-18/lib:$LD_LIBRARY_PATH" >> $GITHUB_ENV
-
       - name: Install rust toolchain
         id: rustc-toolchain
         uses: actions-rs/toolchain@v1
@@ -176,21 +135,12 @@ jobs:
           toolchain: stable
           profile: minimal
           override: true
-          targets: ${{ matrix.target }}
+          target: ${{ matrix.target }}
 
       - uses: Swatinem/rust-cache@v2
         with:
           key: ${{ matrix.target }}
           cache-on-failure: true
-
-      - name: Install go
-        uses: actions/setup-go@v5
-        with:
-          go-version: "^1.22.1"
-
-      - name: Check go installation
-        run: |
-          go version
 
       - name: Set up git private repo access
         run: |
@@ -210,7 +160,7 @@ jobs:
           sudo apt-get install -y gcc-aarch64-linux-gnu
           echo "CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_LINKER=aarch64-linux-gnu-gcc" >> $GITHUB_ENV
 
-      - name: Build binaries with Debugging
+      - name: Build binaries
         env:
           SVM_TARGET_PLATFORM: ${{ matrix.svm_target_platform }}
         shell: bash
@@ -219,7 +169,7 @@ jobs:
           target="${{ matrix.target }}"
           flags=()
 
-          echo "🔍 Starting build process with enhanced debugging..."
+          echo "🔍 Starting build process..."
 
           # Debug: Show system info
           echo "🖥️  System Info:"
@@ -254,21 +204,24 @@ jobs:
           # Handle Windows executable suffix
           [[ "$target" == *windows* ]] && exe=".exe"
 
-          # RUSTFLAGS with correct path and debugging
+          # RUSTFLAGS with correct path for building binaries
+          export RUSTFLAGS="-C target-feature=+crt-static -L${IOMP5_DIR} -liomp5"
+          echo "RUSTFLAGS set to: $RUSTFLAGS"
+
+          # Build bins
+          echo "🚀 Starting cargo bins build..."
+          cargo build --release -p cargo-zisk -p ziskemu -p riscv -p zisk-core --target "$target" "${flags[@]}"
+
+          # RUSTFLAGS with correct path for building libzisk_witness.so
           export RUSTFLAGS="-L${IOMP5_DIR} -liomp5"
           echo "RUSTFLAGS set to: $RUSTFLAGS"
 
-          # Debug: Check Rust and Cargo versions
-          echo "🔍 Rust and Cargo versions:"
-          rustc --version
-          cargo --version
-
-          # Build with debugging
-          echo "🚀 Starting cargo build..."
-          cargo build --release --target "$target" "${flags[@]}"
+          # Build libzisk_witness.so
+          echo "🚀 Starting libzisk_witness.so build..."
+          cargo build --release -p zisk-witness --target "$target" "${flags[@]}"
 
           # Verify built binaries
-          bins=(cargo-zisk ziskemu keccakf_fixed_gen riscv2zisk rom-merkle)
+          bins=(cargo-zisk ziskemu riscv2zisk)
           for name in "${bins[@]}"; do
             bin=./target/$target/release/$name$exe
             echo "🔍 Verifying binary: $bin"
@@ -279,18 +232,19 @@ jobs:
             fi
           done
 
-          # libraries=(libzisk_witness.so)
-          # for name in "${libraries[@]}"; do
-          #   bin=./target/$target/release/$name
-          #   echo "🔍 Verifying binary library: $bin"
-          #   file "$bin" || echo "⚠️  file command failed on $bin"
-          #   ldd "$bin" || echo "⚠️  ldd command failed on $bin"
-          # done
+          # Verify built libraries
+          libraries=(libzisk_witness.so)
+          for name in "${libraries[@]}"; do
+            bin=./target/$target/release/$name
+            echo "🔍 Verifying binary library: $bin"
+            file "$bin" || echo "⚠️  file command failed on $bin"
+            ldd "$bin" || echo "⚠️  ldd command failed on $bin"
+          done
 
           echo "✅ Build process completed."
 
       - name: Set VERSION_NAME
-        run: echo "VERSION_NAME=$([ \"$IS_NIGHTLY\" == 'true' ] && echo 'nightly' || echo '${{ needs.prepare.outputs.tag_name }}')" >> $GITHUB_ENV
+        run: echo "VERSION_NAME=$([ \"$IS_TEST\" == 'true' ] && echo 'test' || echo '${{ needs.prepare.outputs.tag_name }}')" >> $GITHUB_ENV
 
       - name: Archive binaries
         id: artifacts
@@ -302,67 +256,49 @@ jobs:
         shell: bash
         run: |
           if [ "$PLATFORM_NAME" == "linux" ]; then
-            tar -czvf "cargo_zisk_${VERSION_NAME}_${PLATFORM_NAME}_${ARCH}.tar.gz" -C ./target/${TARGET}/release cargo-zisk ziskemu riscv2zisk libzisk_witness.so
-            echo "file_name=cargo_zisk_${VERSION_NAME}_${PLATFORM_NAME}_${ARCH}.tar.gz" >> $GITHUB_OUTPUT
+            tar -czvf "cargo_zisk_${PLATFORM_NAME}_${ARCH}.tar.gz" \
+              --transform 's/.*\///' \
+              ./target/${TARGET}/release/cargo-zisk \
+              ./target/${TARGET}/release/ziskemu \
+              ./target/${TARGET}/release/riscv2zisk \
+              ./target/${TARGET}/release/libzisk_witness.so \
+              ./precompiles/keccakf/src/keccakf_script.json \
+              ./ziskup/ziskup
+
+            echo "file_name=cargo_zisk_${PLATFORM_NAME}_${ARCH}.tar.gz" >> $GITHUB_OUTPUT
           elif [ "$PLATFORM_NAME" == "darwin" ]; then
             # We need to use gtar here otherwise the archive is corrupt.
             # See: https://github.com/actions/virtual-environments/issues/2619
-            gtar -czvf "cargo_zisk_${VERSION_NAME}_${PLATFORM_NAME}_${ARCH}.tar.gz" -C ./target/${TARGET}/release cargo-zisk ziskemu riscv2zisk
-            echo "file_name=cargo_zisk_${VERSION_NAME}_${PLATFORM_NAME}_${ARCH}.tar.gz" >> $GITHUB_OUTPUT
+            gtar -czvf "cargo_zisk_${PLATFORM_NAME}_${ARCH}.tar.gz" \
+              --transform 's/.*\///' \
+              ./target/${TARGET}/release/cargo-zisk \
+              ./target/${TARGET}/release/ziskemu \
+              ./target/${TARGET}/release/riscv2zisk \
+              ./target/${TARGET}/release/libzisk_witness.so \
+              ./precompiles/keccakf/src/keccakf_script.json \
+              ./ziskup/ziskup
+
+            echo "file_name=cargo_zisk_${PLATFORM_NAME}_${ARCH}.tar.gz" >> $GITHUB_OUTPUT
           else
-            cd ./target/${TARGET}/release
-            7z a -tzip "cargo_zisk_${VERSION_NAME}_${PLATFORM_NAME}_${ARCH}.zip" cargo-zisk.exe ziskemu.exe riscv2zisk.exe
-            mv "cargo_zisk_${VERSION_NAME}_${PLATFORM_NAME}_${ARCH}.zip" ../../../
-            echo "file_name=cargo_zisk_${VERSION_NAME}_${PLATFORM_NAME}_${ARCH}.zip" >> $GITHUB_OUTPUT
+            7z a -tzip -ep1 "cargo_zisk_${PLATFORM_NAME}_${ARCH}.zip" \
+              ./target/${TARGET}/cargo-zisk.exe ./target/${TARGET}/ziskemu.exe ./target/${TARGET}/riscv2zisk.exe \
+              ./precompiles/keccakf/src/keccakf_script.json \
+              ./ziskup/ziskup
+
+            mv "cargo_zisk_${PLATFORM_NAME}_${ARCH}.zip" ../../../
+            echo "file_name=cargo_zisk_${PLATFORM_NAME}_${ARCH}.zip" >> $GITHUB_OUTPUT
           fi
 
       # Creates the release for this specific version
       - name: Create release
-        uses: softprops/action-gh-release@v1
+        uses: softprops/action-gh-release@v2
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         with:
           name: ${{ needs.prepare.outputs.release_name }}
           tag_name: ${{ needs.prepare.outputs.tag_name }}
-          prerelease: ${{ env.IS_NIGHTLY == 'true' || needs.prepare.outputs.tag_name == 'latest' }}
-          body: ${{ needs.prepare.outputs.changelog }}
+          draft: ${{ env.IS_TEST == 'true' }}
+          make_latest: "false"
           files: |
             ${{ steps.artifacts.outputs.file_name }}
 
-      # If this is a nightly release, it also updates the release
-      # tagged `nightly` for compatibility with `ziskup`
-      - name: Update nightly release
-        if: ${{ env.IS_NIGHTLY == 'true' }}
-        uses: softprops/action-gh-release@v1
-        with:
-          name: "Nightly"
-          tag_name: "nightly"
-          prerelease: true
-          body: ${{ needs.prepare.outputs.changelog }}
-          files: |
-            ${{ steps.artifacts.outputs.file_name }}
-
-  cleanup:
-    name: Release cleanup
-    runs-on: ubuntu-latest
-    timeout-minutes: 30
-    needs: release
-    if: always()
-    steps:
-      - uses: actions/checkout@v4
-
-      # Moves the `nightly` tag to `HEAD`
-      - name: Move nightly tag
-        if: ${{ env.IS_NIGHTLY }}
-        uses: actions/github-script@v7
-        with:
-          script: |
-            const moveTag = require('./.github/scripts/move-tag.js')
-            await moveTag({ github, context }, 'nightly')
-
-      - name: Delete old nightlies
-        uses: actions/github-script@v7
-        with:
-          script: |
-            const prunePrereleases = require('./.github/scripts/prune-prereleases.js')
-            await prunePrereleases({github, context})
