merge pre-develop 0.5.0 tentative

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -1,17 +1,10 @@
-# Reference: https://github.com/foundry-rs/foundry/blob/master/.github/workflows/release.yml
-
 name: release
 
 on:
   push:
-    branches:
-      - develop
     tags:
       - "v*.*.*"
   workflow_dispatch:
-
-env:
-  CARGO_TERM_COLOR: always
 
 permissions:
   contents: write
@@ -20,81 +13,44 @@ permissions:
 jobs:
   prepare:
     name: Prepare release
-    runs-on: ubuntu-latest
+    runs-on: ubuntu-22.04
     timeout-minutes: 30
     outputs:
       tag_name: ${{ steps.release_info.outputs.tag_name }}
       release_name: ${{ steps.release_info.outputs.release_name }}
-      changelog: ${{ steps.build_changelog.outputs.changelog }}
     steps:
       - uses: actions/checkout@v4
-        with:
-          fetch-depth: 0
 
-      - name: Setup CI
-        uses: ./.github/actions/setup
-        with:
-          pull_token: ${{ secrets.PULL_TOKEN }}
-
-      - name: Set nightly flag
+      - name: Set test flag
         run: |
-          if [[ "${{ github.event_name }}" == "schedule" || "${{ github.event_name }}" == "workflow_dispatch" ]]; then
-            echo "IS_NIGHTLY=true" >> $GITHUB_ENV
+          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
+            echo "IS_TEST=true" >> $GITHUB_ENV
           else
-            echo "IS_NIGHTLY=false" >> $GITHUB_ENV
+            echo "IS_TEST=false" >> $GITHUB_ENV
           fi
 
-      # If it's a nightly release, tag with the release time. If the tag is `develop`, we want to use 
-      # `latest` as the tag name. Else, use the tag name as is.
+      # If it's a test release, tag with the release date. Else, use the tag name as is.
       - name: Compute release name and tag
         id: release_info
         run: |
-          echo "IS_NIGHTLY=$IS_NIGHTLY"
+          echo "IS_TEST=$IS_TEST"
           echo "GITHUB_REF_NAME=$GITHUB_REF_NAME"
-          
-          if [[ $IS_NIGHTLY == "true" ]]; then
-            echo "IS_NIGHTLY"
-            echo "tag_name=nightly-${GITHUB_SHA}"
-            echo "release_name=Nightly ($(date '+%Y-%m-%d'))"
-            echo "tag_name=nightly-${GITHUB_SHA}" >> $GITHUB_OUTPUT
-            echo "release_name=Nightly ($(date '+%Y-%m-%d'))" >> $GITHUB_OUTPUT
-          elif [[ "${GITHUB_REF_NAME}" == "develop" ]]; then
-            echo "IS_LATEST"
-            echo "tag_name=latest"
-            echo "release_name=Latest"
-            echo "tag_name=latest" >> $GITHUB_OUTPUT
-            echo "release_name=Latest" >> $GITHUB_OUTPUT
+
+          if [[ $IS_TEST == "true" ]]; then
+            echo "IS_TEST"
+            echo "tag_name=test-${GITHUB_SHA}"
+            echo "release_name=Test ($(date '+%Y-%m-%d'))"
+            echo "tag_name=test-${GITHUB_SHA}" >> $GITHUB_OUTPUT
+            echo "release_name=Test ($(date '+%Y-%m-%d'))" >> $GITHUB_OUTPUT
           else
+            echo "tag_name=${GITHUB_REF_NAME}"
+            echo "release_name=${GITHUB_REF_NAME}"
             echo "tag_name=${GITHUB_REF_NAME}" >> $GITHUB_OUTPUT
             echo "release_name=${GITHUB_REF_NAME}" >> $GITHUB_OUTPUT
           fi
 
-      # Creates a `nightly-SHA` tag for this specific nightly
-      # This tag is used for this specific nightly version's release
-      # which allows users to roll back. It is also used to build
-      # the changelog.
-      - name: Create build-specific nightly tag
-        if: ${{ env.IS_NIGHTLY == 'true' }}
-        uses: actions/github-script@v7
-        env:
-          TAG_NAME: ${{ steps.release_info.outputs.tag_name }}
-        with:
-          script: |
-            const createTag = require('./.github/scripts/create-tag.js')
-            await createTag({ github, context }, process.env.TAG_NAME)
-
-      - name: Build changelog
-        id: build_changelog
-        uses: mikepenz/release-changelog-builder-action@v4
-        with:
-          configuration: "./.github/changelog.json"
-          fromTag: ${{ env.IS_NIGHTLY == 'true' && 'nightly' || '' }}
-          toTag: ${{ steps.release_info.outputs.tag_name }}
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-
   release:
-    name: ${{ matrix.target }} (${{ matrix.runner }})
+    name: Build ${{ matrix.target }} (${{ matrix.runner }})
     runs-on: ${{ matrix.runner }}
     timeout-minutes: 240
     needs: prepare
@@ -106,16 +62,16 @@ jobs:
           # `target`: Rust build target triple
           # `platform` and `arch`: Used in tarball names
           # `svm`: target platform to use for the Solc binary: https://github.com/roynalnaruto/svm-rs/blob/84cbe0ac705becabdc13168bae28a45ad2299749/svm-builds/build.rs#L4-L24
-          - runner: ubuntu-latest
+          - runner: ubuntu-22.04
             target: x86_64-unknown-linux-gnu
             svm_target_platform: linux-amd64
             platform: linux
             arch: amd64
-         # - runner: warp-ubuntu-latest-arm64-4x
-         #   target: aarch64-unknown-linux-gnu
-         #   svm_target_platform: linux-aarch64
-         #   platform: linux
-         #   arch: arm64
+          # - runner: warp-ubuntu-latest-arm64-4x
+          #   target: aarch64-unknown-linux-gnu
+          #   svm_target_platform: linux-aarch64
+          #   platform: linux
+          #   arch: arm64
           # - runner: macos-13
           #   target: x86_64-apple-darwin
           #   svm_target_platform: macosx-amd64
@@ -130,95 +86,42 @@ jobs:
           #   target: x86_64-pc-windows-msvc
           #   svm_target_platform: windows-amd64
           #   platform: win32
-          #   arch: amd64
+          #   arch: amd64            
     steps:
       - uses: actions/checkout@v4
-
-      - name: Install Protoc
-        uses: arduino/setup-protoc@v3
-        with:
-          repo-token: ${{ secrets.GITHUB_TOKEN }}
-
-      - name: Install libraries
-        shell: bash
-        run: sudo apt-get install -y clang nlohmann-json3-dev build-essential libbenchmark-dev libomp-dev libgmp-dev  nasm libsodium-dev cmake openmpi-bin openmpi-common libopenmpi-dev
-
-      # - name: Verify libiomp5 installation
-      #   run: |
-      #     find /usr -name "libiomp5*"
-      #     ls -l /usr/lib/x86_64-linux-gnu/libiomp5.*
-      #     echo $LD_LIBRARY_PATH
-
-      # - name: Set LD_LIBRARY_PATH
-      #   run: echo "LD_LIBRARY_PATH=/usr/lib/x86_64-linux-gnu:$LD_LIBRARY_PATH" >> $GITHUB_ENV
-
-      - name: Set LD_LIBRARY_PATH for OpenMP
-        run: echo "LD_LIBRARY_PATH=/usr/lib/x86_64-linux-gnu:/usr/lib/llvm-18/lib:$LD_LIBRARY_PATH" >> $GITHUB_ENV
 
       - name: Install rust toolchain
         id: rustc-toolchain
         uses: actions-rs/toolchain@v1
         with:
           toolchain: stable
-          profile: minimal
+          profile: default
           override: true
-          targets: ${{ matrix.target }}
+          target: x86_64-unknown-linux-gnu
 
-      - uses: Swatinem/rust-cache@v2
-        with:
-          key: ${{ matrix.target }}
-          cache-on-failure: true
-
-      - name: Install go
-        uses: actions/setup-go@v5
-        with:
-          go-version: '^1.22.1'
-        
-      - name: Check go installation
-        run: |
-          go version
-
-      - name: Set up git private repo access
-        run: |
-          git config --global url."https://${{ secrets.ZISK_CI_TOKEN }}@github.com/".insteadOf ssh://git@github.com
-          git config --global url."https://${{ secrets.ZISK_CI_TOKEN }}@github.com".insteadOf https://github.com
-
-      - name: Apple M1 setup
-        if: matrix.target == 'aarch64-apple-darwin'
-        run: |
-          echo "SDKROOT=$(xcrun -sdk macosx --show-sdk-path)" >> $GITHUB_ENV
-          echo "MACOSX_DEPLOYMENT_TARGET=$(xcrun -sdk macosx --show-sdk-platform-version)" >> $GITHUB_ENV
-
-      - name: Linux ARM setup
-        if: matrix.target == 'aarch64-unknown-linux-gnu'
-        run: |
-          sudo apt-get update -y
-          sudo apt-get install -y gcc-aarch64-linux-gnu
-          echo "CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_LINKER=aarch64-linux-gnu-gcc" >> $GITHUB_ENV
-
-      - name: Build binaries
-        env:
-          SVM_TARGET_PLATFORM: ${{ matrix.svm_target_platform }}
+      - name: Install dependencies
         shell: bash
         run: |
-          set -eo pipefail
-          target="${{ matrix.target }}"
-          flags=()
+            sudo apt-get install -y xz-utils jq curl build-essential qemu-system libomp-dev \
+                libgmp-dev nlohmann-json3-dev protobuf-compiler uuid-dev libgrpc++-dev \
+                libsecp256k1-dev libsodium-dev libpqxx-dev nasm
 
-          [[ "$target" == *windows* ]] && exe=".exe"
-
-          RUSTFLAGS='-C target-feature=+crt-static' cargo build --release -p cargo-zisk -p ziskemu -p riscv -p zisk-core --target "$target" "${flags[@]}"
-
-          bins=(cargo-zisk ziskemu)
-          for name in "${bins[@]}"; do
-            bin=./target/$target/release/$name$exe
-            file "$bin" || true
-            ldd "$bin" || true
-            $bin --version || true
-          done
-      
-      - name: Set VERSION_NAME
-        run: echo "VERSION_NAME=$([ \"$IS_NIGHTLY\" == 'true' ] && echo 'nightly' || echo '${{ needs.prepare.outputs.tag_name }}')" >> $GITHUB_ENV
+      - name: Build binaries
+        shell: bash
+        run: |
+            cargo build --release --target "${{ matrix.target }}"
+            
+            # Verify built binaries
+            bins=(cargo-zisk ziskemu riscv2zisk libzisk_witness.so)
+            for name in "${bins[@]}"; do
+                bin=./target/$target/release/$name$exe
+                echo "🔍 Verifying binary: $bin"
+                file "$bin" || echo "⚠️  file command failed on $bin"
+                ldd "$bin" || echo "⚠️  ldd command failed on $bin"
+                if [[ "$name" = "cargo-zisk" ]]; then
+                $bin --version || echo "⚠️  Running $bin --version failed"
+                fi
+            done
 
       - name: Archive binaries
         id: artifacts
@@ -226,71 +129,43 @@ jobs:
           PLATFORM_NAME: ${{ matrix.platform }}
           TARGET: ${{ matrix.target }}
           ARCH: ${{ matrix.arch }}
-          VERSION_NAME: ${{ env.VERSION_NAME }}
         shell: bash
         run: |
-          if [ "$PLATFORM_NAME" == "linux" ]; then
-            tar -czvf "cargo_zisk_${VERSION_NAME}_${PLATFORM_NAME}_${ARCH}.tar.gz" -C ./target/${TARGET}/release cargo-zisk ziskemu riscv2zisk
-            echo "file_name=cargo_zisk_${VERSION_NAME}_${PLATFORM_NAME}_${ARCH}.tar.gz" >> $GITHUB_OUTPUT
-          elif [ "$PLATFORM_NAME" == "darwin" ]; then
-            # We need to use gtar here otherwise the archive is corrupt.
-            # See: https://github.com/actions/virtual-environments/issues/2619
-            gtar -czvf "cargo_zisk_${VERSION_NAME}_${PLATFORM_NAME}_${ARCH}.tar.gz" -C ./target/${TARGET}/release cargo-zisk ziskemu riscv2zisk
-            echo "file_name=cargo_zisk_${VERSION_NAME}_${PLATFORM_NAME}_${ARCH}.tar.gz" >> $GITHUB_OUTPUT
+          if [ "$PLATFORM_NAME" == "linux" ] || [ "$PLATFORM_NAME" == "darwin" ]; then
+            ARCHIVE_FILE="cargo_zisk_${PLATFORM_NAME}_${ARCH}.tar.gz"
+
+            TAR_CMD="tar"
+            [ "$PLATFORM_NAME" == "darwin" ] && TAR_CMD="gtar"
+
+            $TAR_CMD -czvf "$ARCHIVE_FILE" --transform 's/.*\///' \
+              ./target/${TARGET}/release/cargo-zisk \
+              ./target/${TARGET}/release/ziskemu \
+              ./target/${TARGET}/release/riscv2zisk \
+              ./target/${TARGET}/release/libzisk_witness.so \
+              ./precompiles/keccakf/src/keccakf_script.json \
+              ./ziskup/ziskup
           else
-            cd ./target/${TARGET}/release
-            7z a -tzip "cargo_zisk_${VERSION_NAME}_${PLATFORM_NAME}_${ARCH}.zip" cargo-zisk.exe ziskemu.exe riscv2zisk.exe
-            mv "cargo_zisk_${VERSION_NAME}_${PLATFORM_NAME}_${ARCH}.zip" ../../../
-            echo "file_name=cargo_zisk_${VERSION_NAME}_${PLATFORM_NAME}_${ARCH}.zip" >> $GITHUB_OUTPUT
+            ARCHIVE_FILE="cargo_zisk_${PLATFORM_NAME}_${ARCH}.zip"
+            7z a -tzip -ep1 "$ARCHIVE_FILE" \
+              ./target/${TARGET}/release/cargo-zisk.exe \
+              ./target/${TARGET}/releaseziskemu.exe \
+              ./target/${TARGET}/release/riscv2zisk.exe \
+              ./precompiles/keccakf/src/keccakf_script.json \
+              ./ziskup/ziskup
+
+            mv "$ARCHIVE_FILE" ../../../
           fi
 
-      # Creates the release for this specific version
+          echo "file_name=$ARCHIVE_FILE" >> $GITHUB_OUTPUT       
+        
       - name: Create release
-        uses: softprops/action-gh-release@v1
+        uses: softprops/action-gh-release@v2
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         with:
           name: ${{ needs.prepare.outputs.release_name }}
           tag_name: ${{ needs.prepare.outputs.tag_name }}
-          prerelease: ${{ env.IS_NIGHTLY == 'true' || needs.prepare.outputs.tag_name == 'latest' }}
-          body: ${{ needs.prepare.outputs.changelog }}
+          draft: true
+          make_latest: "false"
           files: |
-            ${{ steps.artifacts.outputs.file_name }}
-
-      # If this is a nightly release, it also updates the release
-      # tagged `nightly` for compatibility with `ziskup`
-      - name: Update nightly release
-        if: ${{ env.IS_NIGHTLY == 'true' }}
-        uses: softprops/action-gh-release@v1
-        with:
-          name: "Nightly"
-          tag_name: "nightly"
-          prerelease: true
-          body: ${{ needs.prepare.outputs.changelog }}
-          files: |
-            ${{ steps.artifacts.outputs.file_name }}
-
-  cleanup:
-    name: Release cleanup
-    runs-on: ubuntu-latest
-    timeout-minutes: 30
-    needs: release
-    if: always()
-    steps:
-      - uses: actions/checkout@v4
-
-      # Moves the `nightly` tag to `HEAD`
-      - name: Move nightly tag
-        if: ${{ env.IS_NIGHTLY }}
-        uses: actions/github-script@v7
-        with:
-          script: |
-            const moveTag = require('./.github/scripts/move-tag.js')
-            await moveTag({ github, context }, 'nightly')
-
-      - name: Delete old nightlies
-        uses: actions/github-script@v7
-        with:
-          script: |
-            const prunePrereleases = require('./.github/scripts/prune-prereleases.js')
-            await prunePrereleases({github, context})
+            ${{ steps.artifacts.outputs.file_name }}          
